webapp:
  build: .
  links:
    - mysqlmaster:mysqlmaster
    - mysqlslave:mysqlslave
#  ports:
#    - 9999:80
  environment:
    - MASTER_HOST=mysqlmaster
    - MASTER_DB=foobar
    - MASTER_USER=root
    - MASTER_PASS=foo
    - SLAVE_HOST=mysqlslave
    - SLAVE_DB=foobar
    - SLAVE_USER=root
    - SLAVE_PASS=foo


mysqlmaster:
  image: mysql:5.6
  ports:
    - 3307:3306
  environment:
    - MYSQL_ROOT_PASSWORD=foo
  volumes:
    - /opt/docker/mysql/mysql-master:/var/lib/mysql
    - /opt/docker/mysql/master-conf:/etc/mysql/conf.d

mysqlslave:
  image: mysql:5.6
  ports:
    - 3308:3306
  environment:
    - MYSQL_ROOT_PASSWORD=foo
  volumes:
    - /opt/docker/mysql/mysql-slave1:/var/lib/mysql
    - /opt/docker/mysql/slave1-conf:/etc/mysql/conf.d
  links:
    - mysqlmaster:mysqlmaster
